
public enum FakeLaneType {
	TOP,
	MIDDLE,
	BOTTOM,
	TOP_TO_BONUS1,
	BONUS1_TO_TOP,
	BONUS1_TO_MIDDLE,
	MIDDLE_TO_BONUS1,
	MIDDLE_TO_BONUS2,
	BONUS2_TO_MIDDLE,
	BONUS2_TO_BOTTOM,
	BOTTOM_TO_BONUS2,
        ENEMYBASE_TO_TOP_BONUS1,
        ENEMYBASE_TO_MIDDLE_BONUS1,
        ENEMYBASE_TO_MIDDLE_BONUS2,
        ENEMYBASE_TO_BOTTOM_BONUS2,
}
